# Generated by Django 5.2 on 2025-06-05 03:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileShare_App', '0002_uploadfile_delete_sharedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
